//! Synthetic stream generators.
//!
//! Each [`Source`] is a small parametric model of one kind of structure a
//! real index stream has. The presets in [`presets`] sweep the two parameters
//! that dominate codec behaviour on sorted lists — density (`n/universe`) and
//! burstiness — plus a Zipfian dictionary whose list-length distribution
//! decides how much the short-list tail path matters.
//!
//! Generators are deterministic for a given seed.

use rand::prelude::*;

use crate::stream::{Dataset, Kind};

/// A parametric stream model. Sorted variants produce strictly increasing
/// lists in `[0, universe)`; unsorted ones produce arbitrary values.
#[derive(Clone, Debug)]
pub enum Source {
    /// Each position in the universe is present independently with
    /// probability `density`. The uniform-model entropy bound is tight here,
    /// so excess bits/int is pure codec overhead.
    Uniform { universe: u32, lists: u32, density: f64 },
}

impl Source {
    pub fn kind(&self) -> Kind {
        match self {
            Source::Uniform { .. } => Kind::Sorted,
        }
    }

    pub fn universe(&self) -> u32 {
        match self {
            Source::Uniform { universe, .. } => *universe,
        }
    }

    /// One-line description for the dataset header and report.
    pub fn describe(&self) -> String {
        match self {
            Source::Uniform { universe, lists, density } => {
                format!("uniform universe={universe} lists={lists} density={density}")
            }
        }
    }
}

/// A named preset for the `gen` command.
#[derive(Clone, Debug)]
pub struct Preset {
    pub name: &'static str,
    pub source: Source,
}

/// The default sweep written by `gen`. `scale` multiplies universe and list
/// counts so a quick run and a full run share the same shapes.
pub fn presets(scale: u32) -> Vec<Preset> {
    let u = 1_000_000 * scale;
    vec![
        Preset { name: "uniform-d0.001", source: Source::Uniform { universe: u, lists: 64, density: 0.001 } },
        Preset { name: "uniform-d0.01", source: Source::Uniform { universe: u, lists: 64, density: 0.01 } },
        Preset { name: "uniform-d0.1", source: Source::Uniform { universe: u, lists: 32, density: 0.1 } },
        Preset { name: "uniform-d0.5", source: Source::Uniform { universe: u, lists: 8, density: 0.5 } },
    ]
}

pub fn generate(name: &str, source: &Source, seed: u64) -> Dataset {
    let mut rng = StdRng::seed_from_u64(seed);
    let mut ds = Dataset::new(name, source.kind(), source.universe(), source.describe());
    match source {
        Source::Uniform { universe, lists, density } => {
            for _ in 0..*lists {
                ds.lists.push(uniform_list(&mut rng, *universe, *density));
            }
        }
    }
    ds
}

/// Bernoulli sample of `[0, universe)`, generated by geometric gaps so cost
/// is proportional to output not universe.
fn uniform_list(rng: &mut StdRng, universe: u32, density: f64) -> Vec<u32> {
    let mut out = Vec::with_capacity((universe as f64 * density) as usize + 16);
    let mut pos = geometric_gap(rng, density);
    while pos < u64::from(universe) {
        out.push(pos as u32);
        pos += 1 + geometric_gap(rng, density);
    }
    out
}

/// Number of failures before the first success at probability `p`.
fn geometric_gap(rng: &mut StdRng, p: f64) -> u64 {
    if p >= 1.0 {
        return 0;
    }
    let u: f64 = rng.random_range(f64::EPSILON..1.0);
    (u.ln() / (1.0 - p).ln()).floor() as u64
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uniform_density_is_close() {
        let ds = generate("t", &Source::Uniform { universe: 1_000_000, lists: 4, density: 0.01 }, 1);
        assert!(ds.validate().is_ok());
        for l in &ds.lists {
            let d = l.len() as f64 / 1e6;
            assert!((0.008..0.012).contains(&d), "density {d}");
        }
    }

    #[test]
    fn deterministic_for_seed() {
        let s = Source::Uniform { universe: 100_000, lists: 2, density: 0.05 };
        assert_eq!(generate("a", &s, 7).lists, generate("a", &s, 7).lists);
    }
}
